#! /bin/bash
#
# Copyright © 2009 Adeodato Simó (dato@net.com.org.es)
# Copyright © 2013-2015 Guillem Jover <guillem@debian.org>
#
# This software may be used and distributed according to the terms
# of the MIT License, incorporated herein by reference.

# Purpose: this hook will tag Debian bugs as pending. The mail will
# include the commit message, and the portion of the diff corresponding
# to debian/changelog, plus a pointer to the URL that contains the full
# diff. It has some heuristics not to tag the same bug pending twice.
#
# Usage: make this script your post-receive hook, or exec this script
# from there. If you need to execute more than one script against
# post-receive's stdin, you can use pee(1), from the moreutils package.
# No configuration is necessary.

set -e
set -u

# Web interfaces supported: cgit, gitweb
REPOWEB=cgit
REPODIR=`readlink -f "$PWD"`
REPOREL=${REPODIR#/srv/git.debian.org/git/}
REPOREL=${REPOREL#/srv/alioth.debian.org/chroot/home/}
REPOREL=${REPOREL/\/public_git\//\/}
PACKAGE=$(basename "$REPOREL" .git)
BASEURL="https://anonscm.debian.org"
SENDMAIL="/usr/sbin/sendmail -oi -t"

case "$REPOWEB" in
cgit)
    REPOURL="$BASEURL/cgit/$REPOREL/diff/?id="
    ;;
gitweb)
    REPOURL="$BASEURL/?p=$REPOREL;a=commitdiff;h="
    ;;
esac

tempdir=`mktemp -d`
trap "rm -rf \"${tempdir}\"" EXIT

DPKG_VERSION=$(perl -MDpkg -e 'print $Dpkg::version')

case "$DPKG_VERSION" in
1.16.*)
  get_bugs()
  {
    local rev="$1"
    local c="$tempdir/${rev}.changelog"

    git show ${rev}:debian/changelog >"$c" 2>/dev/null
    dpkg-parsechangelog -l"$c" | sed -rne 's/^Closes: *//pi'
  }
  ;;
*)
  get_bugs()
  {
    local rev="$1"

    git show ${rev}:debian/changelog 2>/dev/null \
      | dpkg-parsechangelog -l- -SCloses
  }
  ;;
esac

send_mail() { # send_mail bugno revno diff_file
    local bug="$1"
    local rev="$2"
    local diff="$3"
    local from=$(git show -s --pretty='format:%cn <%ce>' $rev |
                 perl -CI -MEncode -e 'print Encode::encode("MIME-Q", <STDIN>)')
    (cat <<EOF
From: $from
To: $bug-submitter@bugs.debian.org
Subject: Bug#$bug in package $PACKAGE marked as pending
Content-Type: text/plain; charset=utf-8
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
X-Mailer: http://git.hadrons.org/cgit/debian/git-hooks.git/tree/git-post-receive-tag-pending

Control: tag $bug pending

Hi!

Bug #$bug in package $PACKAGE reported by you has been fixed in
the $REPOREL Git repository. You can see the changelog below, and
you can check the diff of the fix at:

    ${REPOURL}`git show -s --pretty='format:%h' "$rev"`

---
EOF
    cat "$diff") | $SENDMAIL
}

while read oldrev newrev refname; do
    git rev-parse --not --branches | grep -v $(git rev-parse $refname) |
    git rev-list --reverse --stdin "${oldrev}..${newrev}" |
    while read rev; do
        d="$tempdir/$rev.diff"
        git show ${rev} -- debian/changelog >"$d"
        bugs=`get_bugs ${rev}`
        for bug in $bugs; do
            if  grep -qE '^\+.*\<'$bug'\>' "$d" &&
              ! grep -qE  '^-.*\<'$bug'\>' "$d"; then
              send_mail $bug "$rev" "$d"
            fi
        done
    done
done

# vi: et
